(in-package :btcl-digest)

(defun dsha256-checksum (data)
  (let ((digester (ironclad:make-digest :sha256)))
    (ironclad:update-digest digester data)
    (let ((1st-round (ironclad:produce-digest digester)))
      (reinitialize-instance digester)
      (ironclad:update-digest digester 1st-round)
      (let ((2nd-round (ironclad:produce-digest digester))
            (checksum 0))
        (setf (ldb (byte 8 0) checksum) (elt 2nd-round 0))
        (setf (ldb (byte 8 8) checksum) (elt 2nd-round 1))
        (setf (ldb (byte 8 16) checksum) (elt 2nd-round 2))
        (setf (ldb (byte 8 24) checksum) (elt 2nd-round 3))
        checksum))))
