(in-package :btcl-net)

(defconstant +TESTNET3-MAGIC+ '(#x07 #x09 #x11 #x0b))

(binary-types:define-binary-string header-command 12)
(binary-types:define-binary-string net-addr-ip-addr 16)
(binary-types:define-binary-struct header-magic-number ()
  (mag0 #\null :binary-type binary-types:char8)
  (mag1 #\null :binary-type binary-types:char8)
  (mag2 #\null :binary-type binary-types:char8)
  (mag3 #\null :binary-type binary-types:char8))
(binary-types:define-binary-struct version-net-addr ()
  (services nil :binary-type binary-types:u64)
  (ip-addr nil :binary-type net-addr-ip-addr)
  (port nil :binary-type binary-types:u16))

(binary-types:define-binary-class header ()
  ((magic :binary-type header-magic-number)
   (command :binary-type header-command)
   (length :binary-type binary-types:u32)
   (checksum :binary-type binary-types:u32))))

(binary-types:define-binary-class msg-version ()
  ((version :binary-type binary-types:s32)
   (services :binary-type binary-types:u64)
   (timestamp :binary-type binary-types:s64)
   (addr-recv :binary-type version-net-addr)
   (addr-from :binary-type version-net-addr)
   (nonce :binary-type binary-types:u64)
   (user-agent :binary-type binary-types:char8)
   (start-height :binary-type binary-types:s32)
   (relay :binary-type binary-types:u8)))
